version: '3.11'

services:
  web:
    build: ./
    volumes:
      - ./:/usr/src/
    ports:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=register_db

volumes:
  postgres_data: